# Generated by Django 2.2.5 on 2021-01-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='usre',
            new_name='user',
        ),
    ]
